language: android
jdk: oraclejdk8

android:
  components:
    # Use the latest revision of Android SDK Tools
    - platform-tools
    - tools
    # The BuildTools version used by your project
    - build-tools-26.0.0
    - build-tools-26.0.1
    - build-tools-27.0.2
    # The SDK version used to compile your project
    - android-26
    - android-27
    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
    # Specify at least one system image, if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-26
    - sys-img-armeabi-v7a-android-27

script:
  - ./gradlew clean :app:assemble :instantapp:assemble

branches:
  only:
    - master